// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: axinomixrunner/axinomixrunner/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgStartRace struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount  string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Mode    string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (m *MsgStartRace) Reset()         { *m = MsgStartRace{} }
func (m *MsgStartRace) String() string { return proto.CompactTextString(m) }
func (*MsgStartRace) ProtoMessage()    {}
func (*MsgStartRace) Descriptor() ([]byte, []int) {
	return fileDescriptor_5837299b41c6f02e, []int{0}
}
func (m *MsgStartRace) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStartRace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStartRace.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStartRace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStartRace.Merge(m, src)
}
func (m *MsgStartRace) XXX_Size() int {
	return m.Size()
}
func (m *MsgStartRace) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStartRace.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStartRace proto.InternalMessageInfo

func (m *MsgStartRace) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgStartRace) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgStartRace) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

type MsgStartRaceResponse struct {
	Id                 uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NeedToCollectCoins uint64 `protobuf:"varint,2,opt,name=needToCollectCoins,proto3" json:"needToCollectCoins,omitempty"`
}

func (m *MsgStartRaceResponse) Reset()         { *m = MsgStartRaceResponse{} }
func (m *MsgStartRaceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgStartRaceResponse) ProtoMessage()    {}
func (*MsgStartRaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5837299b41c6f02e, []int{1}
}
func (m *MsgStartRaceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStartRaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStartRaceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStartRaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStartRaceResponse.Merge(m, src)
}
func (m *MsgStartRaceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgStartRaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStartRaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStartRaceResponse proto.InternalMessageInfo

func (m *MsgStartRaceResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgStartRaceResponse) GetNeedToCollectCoins() uint64 {
	if m != nil {
		return m.NeedToCollectCoins
	}
	return 0
}

type MsgEndRace struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Coins   uint64 `protobuf:"varint,2,opt,name=coins,proto3" json:"coins,omitempty"`
	Score   uint64 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Id      uint64 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgEndRace) Reset()         { *m = MsgEndRace{} }
func (m *MsgEndRace) String() string { return proto.CompactTextString(m) }
func (*MsgEndRace) ProtoMessage()    {}
func (*MsgEndRace) Descriptor() ([]byte, []int) {
	return fileDescriptor_5837299b41c6f02e, []int{2}
}
func (m *MsgEndRace) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEndRace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEndRace.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEndRace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEndRace.Merge(m, src)
}
func (m *MsgEndRace) XXX_Size() int {
	return m.Size()
}
func (m *MsgEndRace) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEndRace.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEndRace proto.InternalMessageInfo

func (m *MsgEndRace) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgEndRace) GetCoins() uint64 {
	if m != nil {
		return m.Coins
	}
	return 0
}

func (m *MsgEndRace) GetScore() uint64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *MsgEndRace) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgEndRaceResponse struct {
	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WinAmount string `protobuf:"bytes,2,opt,name=winAmount,proto3" json:"winAmount,omitempty"`
}

func (m *MsgEndRaceResponse) Reset()         { *m = MsgEndRaceResponse{} }
func (m *MsgEndRaceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgEndRaceResponse) ProtoMessage()    {}
func (*MsgEndRaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5837299b41c6f02e, []int{3}
}
func (m *MsgEndRaceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEndRaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEndRaceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEndRaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEndRaceResponse.Merge(m, src)
}
func (m *MsgEndRaceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgEndRaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEndRaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEndRaceResponse proto.InternalMessageInfo

func (m *MsgEndRaceResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgEndRaceResponse) GetWinAmount() string {
	if m != nil {
		return m.WinAmount
	}
	return ""
}

type MsgBankReplenishment struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount  string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgBankReplenishment) Reset()         { *m = MsgBankReplenishment{} }
func (m *MsgBankReplenishment) String() string { return proto.CompactTextString(m) }
func (*MsgBankReplenishment) ProtoMessage()    {}
func (*MsgBankReplenishment) Descriptor() ([]byte, []int) {
	return fileDescriptor_5837299b41c6f02e, []int{4}
}
func (m *MsgBankReplenishment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBankReplenishment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBankReplenishment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBankReplenishment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBankReplenishment.Merge(m, src)
}
func (m *MsgBankReplenishment) XXX_Size() int {
	return m.Size()
}
func (m *MsgBankReplenishment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBankReplenishment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBankReplenishment proto.InternalMessageInfo

func (m *MsgBankReplenishment) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgBankReplenishment) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MsgBankReplenishmentResponse struct {
}

func (m *MsgBankReplenishmentResponse) Reset()         { *m = MsgBankReplenishmentResponse{} }
func (m *MsgBankReplenishmentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBankReplenishmentResponse) ProtoMessage()    {}
func (*MsgBankReplenishmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5837299b41c6f02e, []int{5}
}
func (m *MsgBankReplenishmentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBankReplenishmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBankReplenishmentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBankReplenishmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBankReplenishmentResponse.Merge(m, src)
}
func (m *MsgBankReplenishmentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBankReplenishmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBankReplenishmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBankReplenishmentResponse proto.InternalMessageInfo

type MsgWithdrawBank struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount  string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgWithdrawBank) Reset()         { *m = MsgWithdrawBank{} }
func (m *MsgWithdrawBank) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawBank) ProtoMessage()    {}
func (*MsgWithdrawBank) Descriptor() ([]byte, []int) {
	return fileDescriptor_5837299b41c6f02e, []int{6}
}
func (m *MsgWithdrawBank) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawBank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawBank.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawBank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawBank.Merge(m, src)
}
func (m *MsgWithdrawBank) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawBank) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawBank.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawBank proto.InternalMessageInfo

func (m *MsgWithdrawBank) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgWithdrawBank) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MsgWithdrawBankResponse struct {
}

func (m *MsgWithdrawBankResponse) Reset()         { *m = MsgWithdrawBankResponse{} }
func (m *MsgWithdrawBankResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawBankResponse) ProtoMessage()    {}
func (*MsgWithdrawBankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5837299b41c6f02e, []int{7}
}
func (m *MsgWithdrawBankResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawBankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawBankResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawBankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawBankResponse.Merge(m, src)
}
func (m *MsgWithdrawBankResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawBankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawBankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawBankResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgStartRace)(nil), "axinomixrunner.axinomixrunner.MsgStartRace")
	proto.RegisterType((*MsgStartRaceResponse)(nil), "axinomixrunner.axinomixrunner.MsgStartRaceResponse")
	proto.RegisterType((*MsgEndRace)(nil), "axinomixrunner.axinomixrunner.MsgEndRace")
	proto.RegisterType((*MsgEndRaceResponse)(nil), "axinomixrunner.axinomixrunner.MsgEndRaceResponse")
	proto.RegisterType((*MsgBankReplenishment)(nil), "axinomixrunner.axinomixrunner.MsgBankReplenishment")
	proto.RegisterType((*MsgBankReplenishmentResponse)(nil), "axinomixrunner.axinomixrunner.MsgBankReplenishmentResponse")
	proto.RegisterType((*MsgWithdrawBank)(nil), "axinomixrunner.axinomixrunner.MsgWithdrawBank")
	proto.RegisterType((*MsgWithdrawBankResponse)(nil), "axinomixrunner.axinomixrunner.MsgWithdrawBankResponse")
}

func init() {
	proto.RegisterFile("axinomixrunner/axinomixrunner/tx.proto", fileDescriptor_5837299b41c6f02e)
}

var fileDescriptor_5837299b41c6f02e = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xb5, 0x6c, 0xd5, 0xc6, 0x83, 0x69, 0xe9, 0x62, 0x5a, 0x55, 0xb8, 0xa2, 0xe8, 0x50, 0x5a,
	0x4a, 0x55, 0x5a, 0x43, 0x2f, 0xbd, 0xb4, 0x36, 0x85, 0x5c, 0x74, 0x51, 0x4c, 0x02, 0xb9, 0xc9,
	0xd2, 0x22, 0x2f, 0xb1, 0x76, 0xc5, 0xee, 0x3a, 0x56, 0x7e, 0x40, 0xee, 0xf9, 0x59, 0x39, 0xfa,
	0x98, 0x4b, 0x20, 0xd8, 0x7f, 0x24, 0x58, 0x96, 0x64, 0xf9, 0x23, 0xf1, 0xc7, 0x4d, 0x6f, 0xe6,
	0xcd, 0x9b, 0xa7, 0x99, 0x65, 0xe0, 0xb3, 0x1b, 0x13, 0xca, 0x42, 0x12, 0xf3, 0x11, 0xa5, 0x98,
	0xff, 0x58, 0x83, 0x32, 0xb6, 0x22, 0xce, 0x24, 0x43, 0x1f, 0x57, 0x13, 0xd6, 0x2a, 0x34, 0x7b,
	0xd0, 0xb0, 0x45, 0x70, 0x2a, 0x5d, 0x2e, 0x1d, 0xd7, 0xc3, 0x48, 0x83, 0x9a, 0xc7, 0xb1, 0x2b,
	0x19, 0xd7, 0x94, 0x4f, 0xca, 0x97, 0xba, 0x93, 0x41, 0xf4, 0x0e, 0xaa, 0x6e, 0xc8, 0x46, 0x54,
	0x6a, 0xe5, 0x24, 0x91, 0x22, 0x84, 0x40, 0x0d, 0x99, 0x8f, 0xb5, 0x4a, 0x12, 0x4d, 0xbe, 0xcd,
	0x33, 0x68, 0x16, 0x55, 0x1d, 0x2c, 0x22, 0x46, 0x05, 0x46, 0xaf, 0xa1, 0x4c, 0xfc, 0x44, 0x58,
	0x75, 0xca, 0xc4, 0x47, 0x16, 0x20, 0x8a, 0xb1, 0xdf, 0x63, 0x5d, 0x36, 0x1c, 0x62, 0x4f, 0x76,
	0x19, 0xa1, 0x22, 0xd1, 0x57, 0x9d, 0x2d, 0x19, 0xb3, 0x0f, 0x60, 0x8b, 0xe0, 0x3f, 0xf5, 0x77,
	0x78, 0x6d, 0xc2, 0x2b, 0xaf, 0x20, 0xb5, 0x00, 0xf3, 0xa8, 0xf0, 0x18, 0x5f, 0x58, 0x55, 0x9d,
	0x05, 0x48, 0x3d, 0xa9, 0x99, 0x27, 0xb3, 0x03, 0x68, 0xd9, 0xe3, 0x59, 0xe7, 0x2d, 0xa8, 0x8f,
	0x09, 0xfd, 0x57, 0x1c, 0xc8, 0x32, 0x60, 0x9e, 0x24, 0xff, 0xdf, 0x71, 0xe9, 0xa5, 0x83, 0xa3,
	0x21, 0xa6, 0x44, 0x0c, 0x42, 0x4c, 0xe5, 0xe1, 0xd3, 0x35, 0x0d, 0x68, 0x6d, 0x53, 0xca, 0x7c,
	0x99, 0x5d, 0x78, 0x63, 0x8b, 0xe0, 0x9c, 0xc8, 0x81, 0xcf, 0xdd, 0xf1, 0x9c, 0x77, 0x44, 0x93,
	0x0f, 0xf0, 0x7e, 0x4d, 0x24, 0xd3, 0xff, 0xf5, 0x50, 0x81, 0x8a, 0x2d, 0x02, 0x14, 0x42, 0x7d,
	0xf9, 0x48, 0xbe, 0x59, 0x2f, 0x3e, 0x2a, 0xab, 0xb8, 0x7b, 0xbd, 0x7d, 0x00, 0x39, 0x1f, 0x77,
	0x00, 0xb5, 0x6c, 0xcb, 0x5f, 0x77, 0xd7, 0xa7, 0x54, 0xfd, 0xe7, 0xde, 0xd4, 0xbc, 0xd1, 0x8d,
	0x02, 0x6f, 0x37, 0xf7, 0xb4, 0x87, 0xe7, 0x8d, 0x22, 0xfd, 0xcf, 0x11, 0x45, 0xb9, 0x8f, 0x2b,
	0x68, 0xac, 0x2c, 0xd1, 0xda, 0x2d, 0x56, 0xe4, 0xeb, 0xbf, 0x0f, 0xe3, 0x67, 0x7d, 0x3b, 0x7f,
	0xef, 0xa6, 0x86, 0x32, 0x99, 0x1a, 0xca, 0xe3, 0xd4, 0x50, 0x6e, 0x67, 0x46, 0x69, 0x32, 0x33,
	0x4a, 0xf7, 0x33, 0xa3, 0x74, 0x91, 0x1f, 0x98, 0xef, 0xe9, 0x49, 0x89, 0x37, 0x6e, 0xcc, 0x75,
	0x84, 0x45, 0xbf, 0x9a, 0xdc, 0x99, 0xf6, 0x53, 0x00, 0x00, 0x00, 0xff, 0xff, 0x14, 0x09, 0x2d,
	0xce, 0x91, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	StartRace(ctx context.Context, in *MsgStartRace, opts ...grpc.CallOption) (*MsgStartRaceResponse, error)
	EndRace(ctx context.Context, in *MsgEndRace, opts ...grpc.CallOption) (*MsgEndRaceResponse, error)
	BankReplenishment(ctx context.Context, in *MsgBankReplenishment, opts ...grpc.CallOption) (*MsgBankReplenishmentResponse, error)
	WithdrawBank(ctx context.Context, in *MsgWithdrawBank, opts ...grpc.CallOption) (*MsgWithdrawBankResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) StartRace(ctx context.Context, in *MsgStartRace, opts ...grpc.CallOption) (*MsgStartRaceResponse, error) {
	out := new(MsgStartRaceResponse)
	err := c.cc.Invoke(ctx, "/axinomixrunner.axinomixrunner.Msg/StartRace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) EndRace(ctx context.Context, in *MsgEndRace, opts ...grpc.CallOption) (*MsgEndRaceResponse, error) {
	out := new(MsgEndRaceResponse)
	err := c.cc.Invoke(ctx, "/axinomixrunner.axinomixrunner.Msg/EndRace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BankReplenishment(ctx context.Context, in *MsgBankReplenishment, opts ...grpc.CallOption) (*MsgBankReplenishmentResponse, error) {
	out := new(MsgBankReplenishmentResponse)
	err := c.cc.Invoke(ctx, "/axinomixrunner.axinomixrunner.Msg/BankReplenishment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawBank(ctx context.Context, in *MsgWithdrawBank, opts ...grpc.CallOption) (*MsgWithdrawBankResponse, error) {
	out := new(MsgWithdrawBankResponse)
	err := c.cc.Invoke(ctx, "/axinomixrunner.axinomixrunner.Msg/WithdrawBank", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	StartRace(context.Context, *MsgStartRace) (*MsgStartRaceResponse, error)
	EndRace(context.Context, *MsgEndRace) (*MsgEndRaceResponse, error)
	BankReplenishment(context.Context, *MsgBankReplenishment) (*MsgBankReplenishmentResponse, error)
	WithdrawBank(context.Context, *MsgWithdrawBank) (*MsgWithdrawBankResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) StartRace(ctx context.Context, req *MsgStartRace) (*MsgStartRaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRace not implemented")
}
func (*UnimplementedMsgServer) EndRace(ctx context.Context, req *MsgEndRace) (*MsgEndRaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndRace not implemented")
}
func (*UnimplementedMsgServer) BankReplenishment(ctx context.Context, req *MsgBankReplenishment) (*MsgBankReplenishmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BankReplenishment not implemented")
}
func (*UnimplementedMsgServer) WithdrawBank(ctx context.Context, req *MsgWithdrawBank) (*MsgWithdrawBankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawBank not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_StartRace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStartRace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).StartRace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axinomixrunner.axinomixrunner.Msg/StartRace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).StartRace(ctx, req.(*MsgStartRace))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_EndRace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgEndRace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).EndRace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axinomixrunner.axinomixrunner.Msg/EndRace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).EndRace(ctx, req.(*MsgEndRace))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BankReplenishment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBankReplenishment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BankReplenishment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axinomixrunner.axinomixrunner.Msg/BankReplenishment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BankReplenishment(ctx, req.(*MsgBankReplenishment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawBank)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/axinomixrunner.axinomixrunner.Msg/WithdrawBank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawBank(ctx, req.(*MsgWithdrawBank))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "axinomixrunner.axinomixrunner.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRace",
			Handler:    _Msg_StartRace_Handler,
		},
		{
			MethodName: "EndRace",
			Handler:    _Msg_EndRace_Handler,
		},
		{
			MethodName: "BankReplenishment",
			Handler:    _Msg_BankReplenishment_Handler,
		},
		{
			MethodName: "WithdrawBank",
			Handler:    _Msg_WithdrawBank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "axinomixrunner/axinomixrunner/tx.proto",
}

func (m *MsgStartRace) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStartRace) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStartRace) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Mode) > 0 {
		i -= len(m.Mode)
		copy(dAtA[i:], m.Mode)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Mode)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgStartRaceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStartRaceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStartRaceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NeedToCollectCoins != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.NeedToCollectCoins))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgEndRace) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEndRace) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEndRace) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x20
	}
	if m.Score != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Score))
		i--
		dAtA[i] = 0x18
	}
	if m.Coins != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Coins))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgEndRaceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEndRaceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEndRaceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WinAmount) > 0 {
		i -= len(m.WinAmount)
		copy(dAtA[i:], m.WinAmount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.WinAmount)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgBankReplenishment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBankReplenishment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBankReplenishment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBankReplenishmentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBankReplenishmentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBankReplenishmentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawBank) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawBank) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawBank) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawBankResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawBankResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawBankResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgStartRace) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Mode)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgStartRaceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	if m.NeedToCollectCoins != 0 {
		n += 1 + sovTx(uint64(m.NeedToCollectCoins))
	}
	return n
}

func (m *MsgEndRace) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Coins != 0 {
		n += 1 + sovTx(uint64(m.Coins))
	}
	if m.Score != 0 {
		n += 1 + sovTx(uint64(m.Score))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgEndRaceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.WinAmount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBankReplenishment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBankReplenishmentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgWithdrawBank) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWithdrawBankResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgStartRace) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStartRace: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStartRace: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStartRaceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStartRaceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStartRaceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NeedToCollectCoins", wireType)
			}
			m.NeedToCollectCoins = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NeedToCollectCoins |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEndRace) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEndRace: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEndRace: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			m.Coins = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Coins |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			m.Score = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Score |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEndRaceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEndRaceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEndRaceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WinAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WinAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBankReplenishment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBankReplenishment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBankReplenishment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBankReplenishmentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBankReplenishmentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBankReplenishmentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawBank) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawBank: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawBank: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawBankResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawBankResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawBankResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
