version: 1
accounts:
- name: alice
  coins: ["10000000000runner"]
- name: bob
  coins: ["100000000runner"]
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins: ["100runner"]
  host: ":4501"


#  api: "0.0.0.0:1317"
#  rpc: "0.0.0.0:26657"
#  p2p: "0.0.0.0:26656"
#  prof: "0.0.0.0:6060"
#  grpc: "0.0.0.0:9090"
#  grpc-web: "0.0.0.0:9091"

validators:
- name: alice
  bonded: 100000000runner
  app:
    api:
      address: ":1318"
    grpc:
      address: ":9092"
    grpc-web:
      address: ":9093"
  config:
    p2p:
      laddr: ":26659"
    rpc:
      laddr: ":26660"
      pprof_laddr: ":6061"

genesis:
  app_state:
    staking:
      params:
        bond_denom: runner
    bank:
      denom_metadata:
        - name: runner
          symbol: RUNNER
          description: The native staking runner of the Axinomix Runner Network.
          denom_units:
            - denom: urunner
              exponent: 0
              aliases:
                - microrunner
            - denom: mrunner
              exponent: 3
              aliases:
                - millirunner
            - denom: runner
              exponent: 6
          base: urunner
          display: runner
